name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.4
  speech_to_text: ^7.0.0
  google_sign_in: ^6.3.0
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.1
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  geolocator: ^14.0.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_slidable: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
